/**
 * 다국어 번역 동기화 스크립트
 * en.json을 기준으로 모든 언어 파일에 누락된 번역을 추가합니다.
 */

const fs = require('fs');
const path = require('path');

const LOCALES_DIR = path.join(__dirname, '../public/locales');

// 번역 데이터 - 영어를 기준으로 각 언어로 번역
const translations = {
  // ===== contentFactory =====
  contentFactory: {
    ja: {
      title: "コンテンツファクトリー",
      subtitle: "生成するコンテンツタイプを選択",
      productInfo: "製品/サービス情報",
      productInfoPlaceholder: "コンテンツを生成する製品/サービス情報を入力してください\n\n例：皮膚科のニキビ治療プログラムを宣伝したいです。ターゲットは20〜30代女性で、SNSマーケティング用にトレンディで信頼感のあるイメージを希望します。非侵襲治療、即効性、リーズナブルな価格が特徴です。",
      minChars: "最低10文字以上入力してください",
      selectContentType: "1つ以上のコンテンツタイプを選択してください",
      start: "開始",
      selected: "個のコンテンツタイプを選択",
      estimatedTime: "所要時間：2〜5分",
      processTitle: "🏭 5段階コンテンツファクトリープロセス",
      step1Name: "コンセプト",
      step1Desc: "AI製品分析と戦略",
      step2Name: "メッセージ",
      step2Desc: "メイン/サブコピー自動生成",
      step3Name: "スクリプト",
      step3Desc: "リール、漫画、カードニュースシナリオ",
      step4Name: "コピー",
      step4Desc: "各形式に合わせたテキスト最終化",
      step5Name: "制作",
      step5Desc: "すべての画像を自動生成",
      pricingTitle: "💰 コンテンツ価格表",
      contentTypes: {
        reels: "リール/TikTok",
        reelsCount: "10カット",
        comic: "4コマ漫画",
        comicCount: "4コマ",
        cardnews: "カードニュース",
        cardnewsCount: "5枚",
        banner: "バナー広告",
        bannerCount: "2種",
        thumbnail: "YouTubeサムネイル",
        thumbnailCount: "3種",
        detail: "詳細ページ",
        detailCount: "2種"
      },
      modal: {
        title: "コンテンツファクトリー",
        subtitle: "デイリーコンテンツ自動生成",
        step: "ステップ",
        prevStep: "前へ",
        nextStep: "次へ",
        generating: "生成中...",
        complete: "完了"
      },
      stepConcept: {
        inputLabel: "💡 製品/サービス情報入力",
        placeholder: "例：皮膚科専門病院のニキビ治療プログラムを宣伝したいです。ターゲットは20-30代女性で、トレンディで信頼感のあるイメージでSNSマーケティングをする予定です。",
        analyzing: "Perplexity + GPTで分析中...",
        analyze: "コンセプト分析",
        result: "コンセプト分析結果",
        edit: "編集",
        regenerate: "再生成",
        productName: "📦 製品名",
        usp: "✨ USP（強み）",
        target: "🎯 ターゲット",
        toneAndManner: "🎨 トーン＆マナー",
        strategy: "📊 戦略方向",
        marketTrend: "📈 市場トレンド",
        keywords: "🏷️ キーワード",
        editTitle: "✏️ コンセプト編集",
        cancel: "キャンセル",
        save: "保存",
        enterPrompt: "プロンプトを入力してください",
        generateFailed: "コンセプト生成に失敗しました",
        generateError: "コンセプト生成中にエラーが発生しました"
      },
      stepMessage: {
        loading: "GPTがメッセージを作成中...",
        loadingDesc: "コンセプトに基づいて最適なコピーを生成中",
        title: "メッセージ方向設定",
        subtitle: "マーケティングメッセージのコアコピーを選択または編集",
        directEdit: "直接編集",
        regenerate: "再生成",
        mainCopy: "💥 メインコピー",
        mainCopyDesc: "最も目を引くキーメッセージ",
        subCopy: "📝 サブコピー",
        subCopyDesc: "メインコピーを補助する説明",
        cta: "👆 CTA（コールトゥアクション）",
        ctaDesc: "行動を促すボタン/テキスト",
        recommended: "おすすめ",
        editTitle: "✏️ メッセージを直接編集",
        mainCopyLabel: "メインコピー",
        subCopyLabel: "サブコピー",
        ctaLabel: "CTAテキスト",
        cancel: "キャンセル",
        save: "保存",
        generateFailed: "メッセージ生成に失敗しました",
        generateError: "メッセージ生成中にエラーが発生しました"
      },
      stepScript: {
        loading: "GPTが台本を作成中...",
        loadingDesc: "リール、4コマ漫画、カードニュースストーリー生成中",
        title: "台本/シナリオ承認",
        subtitle: "各コンテンツ形式のストーリーラインを確認",
        edit: "編集",
        regenerate: "再生成",
        reelsTiktok: "リール/TikTok",
        comic: "4コマ漫画",
        cardnews: "カードニュース",
        editTitle: "✏️ 台本編集",
        editNotice: "台本編集機能は近日公開予定です。",
        cancel: "キャンセル",
        save: "保存",
        reelsSceneTitle: "🎬 リール/TikTokシーン（10個）",
        seconds: "秒",
        comicTitle: "📖 4コマ漫画ストーリー",
        panel: "コマ",
        cardnewsTitle: "📱 カードニュースフロー（5ページ）",
        generateFailed: "台本生成に失敗しました",
        generateError: "台本生成中にエラーが発生しました"
      },
      stepCopy: {
        loading: "GPTがコピーを確定中...",
        loadingDesc: "各形式の最終テキストを整理中",
        title: "コピー確定",
        subtitle: "各コンテンツの最終テキストを確認",
        edit: "編集",
        regenerate: "再生成",
        reelsCaptions: "🎬 リール字幕",
        cut: "カット",
        cardnewsCopies: "📱 カードニュースコピー",
        page: "ページ",
        bannerCopy: "🖼️ バナーコピー",
        storyCopy: "📲 ストーリーコピー",
        thumbnailTitle: "🎥 サムネイルタイトル",
        detailPageHeadline: "📄 詳細ページヘッドライン",
        editTitle: "✏️ コピー編集",
        reelsCaptionsLabel: "リール字幕",
        cardnewsCopiesLabel: "カードニュースコピー",
        bannerCopyLabel: "バナーコピー",
        storyCopyLabel: "ストーリーコピー",
        thumbnailTitleLabel: "サムネイルタイトル",
        detailPageHeadlineLabel: "詳細ページヘッドライン",
        cancel: "キャンセル",
        save: "保存",
        generateFailed: "コピー生成に失敗しました",
        generateError: "コピー生成中にエラーが発生しました"
      },
      stepProduction: {
        title: "自動コンテンツ生産",
        totalImages: "合計{{count}}枚のコンテンツが生成されます",
        reels10: "🎬 リール 10枚",
        comic4: "📖 漫画 4枚",
        cardnews5: "📱 カードニュース 5枚",
        banner2: "🖼️ バナー 2枚",
        story2: "📲 ストーリー 2枚",
        thumbnail3: "🎥 サムネイル 3枚",
        detail2: "📄 詳細ページ 2枚",
        preparing: "準備中...",
        startProduction: "生産開始",
        estimatedTime: "約3〜5分所要・完了後ギャラリーに自動保存",
        overallProgress: "全体進捗",
        reelsLine: "リール/TikTokシーン",
        comicLine: "4コマ漫画",
        cardnewsLine: "カードニュース",
        bannerLine: "バナー広告",
        storyLine: "ストーリー広告",
        thumbnailLine: "YouTubeサムネイル",
        detailLine: "詳細ページヘッダー",
        images: "枚",
        completed: "完了",
        completeTitle: "🎉 生産完了！",
        completeDesc: "{{count}}枚のコンテンツが正常に生成されました。",
        completeGuide: "ギャラリーで確認してダウンロードしてください。",
        startFailed: "生産開始に失敗しました",
        startError: "生産開始中にエラーが発生しました"
      }
    },
    zh: {
      title: "内容工厂",
      subtitle: "选择要生成的内容类型",
      productInfo: "产品/服务信息",
      productInfoPlaceholder: "请输入要生成内容的产品/服务信息\n\n示例：我想推广皮肤科的痘痘治疗项目。目标群体是20-30岁女性，希望用时尚可信的形象进行SNS营销。特点是非侵入性治疗、快速见效、价格合理。",
      minChars: "请至少输入10个字符",
      selectContentType: "请选择至少1种内容类型",
      start: "开始",
      selected: "个内容类型已选择",
      estimatedTime: "预计用时：2-5分钟",
      processTitle: "🏭 5步内容工厂流程",
      step1Name: "概念",
      step1Desc: "AI产品分析与策略",
      step2Name: "信息",
      step2Desc: "主/副文案自动生成",
      step3Name: "脚本",
      step3Desc: "短视频、漫画、卡片新闻场景",
      step4Name: "文案",
      step4Desc: "各格式文字最终确定",
      step5Name: "制作",
      step5Desc: "自动生成所有图片",
      pricingTitle: "💰 内容价格表",
      contentTypes: {
        reels: "短视频/TikTok",
        reelsCount: "10个画面",
        comic: "4格漫画",
        comicCount: "4格",
        cardnews: "卡片新闻",
        cardnewsCount: "5张",
        banner: "横幅广告",
        bannerCount: "2种",
        thumbnail: "YouTube缩略图",
        thumbnailCount: "3种",
        detail: "详情页",
        detailCount: "2种"
      },
      modal: {
        title: "内容工厂",
        subtitle: "每日内容自动生成",
        step: "步骤",
        prevStep: "上一步",
        nextStep: "下一步",
        generating: "生成中...",
        complete: "完成"
      },
      stepConcept: {
        inputLabel: "💡 产品/服务信息输入",
        placeholder: "示例：我想推广皮肤科专业医院的痘痘治疗项目。目标群体是20-30岁女性，计划用时尚可信的形象进行SNS营销。",
        analyzing: "Perplexity + GPT分析中...",
        analyze: "概念分析",
        result: "概念分析结果",
        edit: "编辑",
        regenerate: "重新生成",
        productName: "📦 产品名称",
        usp: "✨ USP（优势）",
        target: "🎯 目标群体",
        toneAndManner: "🎨 调性风格",
        strategy: "📊 策略方向",
        marketTrend: "📈 市场趋势",
        keywords: "🏷️ 关键词",
        editTitle: "✏️ 编辑概念",
        cancel: "取消",
        save: "保存",
        enterPrompt: "请输入提示词",
        generateFailed: "概念生成失败",
        generateError: "概念生成过程中出错"
      },
      stepMessage: {
        loading: "GPT正在撰写信息...",
        loadingDesc: "基于概念生成最佳文案",
        title: "信息方向设置",
        subtitle: "选择或编辑核心营销文案",
        directEdit: "直接编辑",
        regenerate: "重新生成",
        mainCopy: "💥 主文案",
        mainCopyDesc: "最吸引眼球的核心信息",
        subCopy: "📝 副文案",
        subCopyDesc: "辅助主文案的说明",
        cta: "👆 CTA（行动号召）",
        ctaDesc: "引导行动的按钮/文字",
        recommended: "推荐",
        editTitle: "✏️ 直接编辑信息",
        mainCopyLabel: "主文案",
        subCopyLabel: "副文案",
        ctaLabel: "CTA文字",
        cancel: "取消",
        save: "保存",
        generateFailed: "信息生成失败",
        generateError: "信息生成过程中出错"
      },
      stepScript: {
        loading: "GPT正在撰写脚本...",
        loadingDesc: "生成短视频、4格漫画、卡片新闻故事",
        title: "脚本/场景批准",
        subtitle: "查看各内容格式的故事线",
        edit: "编辑",
        regenerate: "重新生成",
        reelsTiktok: "短视频/TikTok",
        comic: "4格漫画",
        cardnews: "卡片新闻",
        editTitle: "✏️ 编辑脚本",
        editNotice: "脚本编辑功能即将推出。",
        cancel: "取消",
        save: "保存",
        reelsSceneTitle: "🎬 短视频/TikTok场景（10个）",
        seconds: "秒",
        comicTitle: "📖 4格漫画故事",
        panel: "格",
        cardnewsTitle: "📱 卡片新闻流程（5页）",
        generateFailed: "脚本生成失败",
        generateError: "脚本生成过程中出错"
      },
      stepCopy: {
        loading: "GPT正在确定文案...",
        loadingDesc: "整理各格式的最终文字",
        title: "文案确定",
        subtitle: "查看各内容的最终文字",
        edit: "编辑",
        regenerate: "重新生成",
        reelsCaptions: "🎬 短视频字幕",
        cut: "个",
        cardnewsCopies: "📱 卡片新闻文案",
        page: "页",
        bannerCopy: "🖼️ 横幅文案",
        storyCopy: "📲 故事文案",
        thumbnailTitle: "🎥 缩略图标题",
        detailPageHeadline: "📄 详情页标题",
        editTitle: "✏️ 编辑文案",
        reelsCaptionsLabel: "短视频字幕",
        cardnewsCopiesLabel: "卡片新闻文案",
        bannerCopyLabel: "横幅文案",
        storyCopyLabel: "故事文案",
        thumbnailTitleLabel: "缩略图标题",
        detailPageHeadlineLabel: "详情页标题",
        cancel: "取消",
        save: "保存",
        generateFailed: "文案生成失败",
        generateError: "文案生成过程中出错"
      },
      stepProduction: {
        title: "自动内容生产",
        totalImages: "共{{count}}张内容将被生成",
        reels10: "🎬 短视频 10张",
        comic4: "📖 漫画 4张",
        cardnews5: "📱 卡片新闻 5张",
        banner2: "🖼️ 横幅 2张",
        story2: "📲 故事 2张",
        thumbnail3: "🎥 缩略图 3张",
        detail2: "📄 详情页 2张",
        preparing: "准备中...",
        startProduction: "开始生产",
        estimatedTime: "预计3-5分钟・完成后自动保存到相册",
        overallProgress: "总体进度",
        reelsLine: "短视频/TikTok场景",
        comicLine: "4格漫画",
        cardnewsLine: "卡片新闻",
        bannerLine: "横幅广告",
        storyLine: "故事广告",
        thumbnailLine: "YouTube缩略图",
        detailLine: "详情页头部",
        images: "张",
        completed: "完成",
        completeTitle: "🎉 生产完成！",
        completeDesc: "{{count}}张内容已成功生成。",
        completeGuide: "请在相册中查看并下载。",
        startFailed: "生产启动失败",
        startError: "生产启动过程中出错"
      }
    },
    es: {
      title: "Fábrica de Contenido",
      subtitle: "Selecciona los tipos de contenido a generar",
      productInfo: "Información del Producto/Servicio",
      productInfoPlaceholder: "Ingresa la información del producto/servicio para generar contenido\n\nEjemplo: Quiero promocionar un programa de tratamiento de acné de una clínica dermatológica. El público objetivo son mujeres de 20-30 años, y quiero imágenes modernas y confiables para marketing en redes sociales.",
      minChars: "Por favor ingresa al menos 10 caracteres",
      selectContentType: "Por favor selecciona al menos 1 tipo de contenido",
      start: "Iniciar",
      selected: "tipos de contenido seleccionados",
      estimatedTime: "Tiempo estimado: 2-5 minutos",
      processTitle: "🏭 Proceso de 5 Pasos de la Fábrica de Contenido",
      step1Name: "Concepto",
      step1Desc: "Análisis de producto con IA y estrategia",
      step2Name: "Mensaje",
      step2Desc: "Generación automática de copy principal/secundario",
      step3Name: "Guión",
      step3Desc: "Escenarios para Reels, cómics, card news",
      step4Name: "Copy",
      step4Desc: "Finalización de texto para cada formato",
      step5Name: "Producción",
      step5Desc: "Generación automática de todas las imágenes",
      pricingTitle: "💰 Lista de Precios de Contenido",
      contentTypes: {
        reels: "Reels/TikTok",
        reelsCount: "10 escenas",
        comic: "Cómic de 4 Paneles",
        comicCount: "4 paneles",
        cardnews: "Card News",
        cardnewsCount: "5 páginas",
        banner: "Anuncio Banner",
        bannerCount: "2 tipos",
        thumbnail: "Miniatura YouTube",
        thumbnailCount: "3 tipos",
        detail: "Página de Detalle",
        detailCount: "2 tipos"
      },
      modal: {
        title: "Fábrica de Contenido",
        subtitle: "Generación automática de contenido diario",
        step: "Paso",
        prevStep: "Anterior",
        nextStep: "Siguiente",
        generating: "Generando...",
        complete: "Completar"
      },
      stepConcept: {
        inputLabel: "💡 Información del Producto/Servicio",
        placeholder: "Ejemplo: Quiero promocionar un programa de tratamiento de acné de una clínica dermatológica especializada. El público objetivo son mujeres de 20-30 años, y planeo hacer marketing en redes sociales con imágenes modernas y confiables.",
        analyzing: "Analizando con Perplexity + GPT...",
        analyze: "Analizar Concepto",
        result: "Resultado del Análisis de Concepto",
        edit: "Editar",
        regenerate: "Regenerar",
        productName: "📦 Nombre del Producto",
        usp: "✨ USP (Propuesta Única de Venta)",
        target: "🎯 Público Objetivo",
        toneAndManner: "🎨 Tono y Estilo",
        strategy: "📊 Dirección Estratégica",
        marketTrend: "📈 Tendencia del Mercado",
        keywords: "🏷️ Palabras Clave",
        editTitle: "✏️ Editar Concepto",
        cancel: "Cancelar",
        save: "Guardar",
        enterPrompt: "Por favor ingresa un prompt",
        generateFailed: "Error al generar concepto",
        generateError: "Error durante la generación del concepto"
      },
      stepMessage: {
        loading: "GPT está escribiendo mensajes...",
        loadingDesc: "Generando copy óptimo basado en el concepto",
        title: "Dirección del Mensaje",
        subtitle: "Selecciona o edita los copies clave de marketing",
        directEdit: "Edición Directa",
        regenerate: "Regenerar",
        mainCopy: "💥 Copy Principal",
        mainCopyDesc: "El mensaje clave más llamativo",
        subCopy: "📝 Copy Secundario",
        subCopyDesc: "Descripción de apoyo para el copy principal",
        cta: "👆 CTA (Llamada a la Acción)",
        ctaDesc: "Botón/texto que impulsa la acción",
        recommended: "Recomendado",
        editTitle: "✏️ Editar Mensaje Directamente",
        mainCopyLabel: "Copy Principal",
        subCopyLabel: "Copy Secundario",
        ctaLabel: "Texto CTA",
        cancel: "Cancelar",
        save: "Guardar",
        generateFailed: "Error al generar mensaje",
        generateError: "Error durante la generación del mensaje"
      },
      stepScript: {
        loading: "GPT está escribiendo guiones...",
        loadingDesc: "Generando historias de Reels, cómics, card news",
        title: "Aprobación de Guión/Escenario",
        subtitle: "Revisa la línea argumental de cada formato de contenido",
        edit: "Editar",
        regenerate: "Regenerar",
        reelsTiktok: "Reels/TikTok",
        comic: "Cómic de 4 Paneles",
        cardnews: "Card News",
        editTitle: "✏️ Editar Guión",
        editNotice: "La función de edición de guiones estará disponible próximamente.",
        cancel: "Cancelar",
        save: "Guardar",
        reelsSceneTitle: "🎬 Escenas Reels/TikTok (10)",
        seconds: "seg",
        comicTitle: "📖 Historia del Cómic de 4 Paneles",
        panel: "Panel",
        cardnewsTitle: "📱 Flujo de Card News (5 páginas)",
        generateFailed: "Error al generar guión",
        generateError: "Error durante la generación del guión"
      },
      stepCopy: {
        loading: "GPT está finalizando el copy...",
        loadingDesc: "Organizando texto final para cada formato",
        title: "Finalización del Copy",
        subtitle: "Revisa el texto final para cada contenido",
        edit: "Editar",
        regenerate: "Regenerar",
        reelsCaptions: "🎬 Subtítulos de Reels",
        cut: "Escena",
        cardnewsCopies: "📱 Copy de Card News",
        page: "Página",
        bannerCopy: "🖼️ Copy de Banner",
        storyCopy: "📲 Copy de Story",
        thumbnailTitle: "🎥 Título de Miniatura",
        detailPageHeadline: "📄 Titular de Página de Detalle",
        editTitle: "✏️ Editar Copy",
        reelsCaptionsLabel: "Subtítulos de Reels",
        cardnewsCopiesLabel: "Copy de Card News",
        bannerCopyLabel: "Copy de Banner",
        storyCopyLabel: "Copy de Story",
        thumbnailTitleLabel: "Título de Miniatura",
        detailPageHeadlineLabel: "Titular de Página de Detalle",
        cancel: "Cancelar",
        save: "Guardar",
        generateFailed: "Error al generar copy",
        generateError: "Error durante la generación del copy"
      },
      stepProduction: {
        title: "Producción Automática de Contenido",
        totalImages: "Se generarán {{count}} imágenes",
        reels10: "🎬 Reels 10",
        comic4: "📖 Cómic 4",
        cardnews5: "📱 Card News 5",
        banner2: "🖼️ Banner 2",
        story2: "📲 Story 2",
        thumbnail3: "🎥 Miniatura 3",
        detail2: "📄 Página de Detalle 2",
        preparing: "Preparando...",
        startProduction: "Iniciar Producción",
        estimatedTime: "Estimado 3-5 min • Guardado automático en galería",
        overallProgress: "Progreso General",
        reelsLine: "Escenas Reels/TikTok",
        comicLine: "Cómic de 4 Paneles",
        cardnewsLine: "Card News",
        bannerLine: "Anuncios Banner",
        storyLine: "Anuncios Story",
        thumbnailLine: "Miniatura YouTube",
        detailLine: "Encabezado Página de Detalle",
        images: "imágenes",
        completed: "Completado",
        completeTitle: "🎉 ¡Producción Completa!",
        completeDesc: "{{count}} imágenes han sido generadas exitosamente.",
        completeGuide: "Revisa y descarga desde la galería.",
        startFailed: "Error al iniciar producción",
        startError: "Error durante el inicio de producción"
      }
    },
    fr: {
      title: "Usine à Contenu",
      subtitle: "Sélectionnez les types de contenu à générer",
      productInfo: "Informations Produit/Service",
      productInfoPlaceholder: "Entrez les informations du produit/service pour générer du contenu\n\nExemple : Je veux promouvoir un programme de traitement de l'acné d'une clinique dermatologique. Le public cible est les femmes de 20-30 ans, et je veux des images tendance et fiables pour le marketing sur les réseaux sociaux.",
      minChars: "Veuillez entrer au moins 10 caractères",
      selectContentType: "Veuillez sélectionner au moins 1 type de contenu",
      start: "Démarrer",
      selected: "types de contenu sélectionnés",
      estimatedTime: "Temps estimé : 2-5 minutes",
      processTitle: "🏭 Processus en 5 Étapes de l'Usine à Contenu",
      step1Name: "Concept",
      step1Desc: "Analyse IA du produit et stratégie",
      step2Name: "Message",
      step2Desc: "Génération auto du copy principal/secondaire",
      step3Name: "Script",
      step3Desc: "Scénarios Reels, BD, card news",
      step4Name: "Copy",
      step4Desc: "Finalisation du texte pour chaque format",
      step5Name: "Production",
      step5Desc: "Génération auto de toutes les images",
      pricingTitle: "💰 Grille Tarifaire du Contenu",
      contentTypes: {
        reels: "Reels/TikTok",
        reelsCount: "10 scènes",
        comic: "BD 4 Cases",
        comicCount: "4 cases",
        cardnews: "Card News",
        cardnewsCount: "5 pages",
        banner: "Bannière Pub",
        bannerCount: "2 types",
        thumbnail: "Miniature YouTube",
        thumbnailCount: "3 types",
        detail: "Page Détail",
        detailCount: "2 types"
      },
      modal: {
        title: "Usine à Contenu",
        subtitle: "Génération auto de contenu quotidien",
        step: "Étape",
        prevStep: "Précédent",
        nextStep: "Suivant",
        generating: "Génération...",
        complete: "Terminer"
      },
      stepConcept: {
        inputLabel: "💡 Informations Produit/Service",
        placeholder: "Exemple : Je veux promouvoir un programme de traitement de l'acné d'une clinique dermatologique spécialisée. Le public cible est les femmes de 20-30 ans, et je prévois de faire du marketing sur les réseaux sociaux avec des images tendance et fiables.",
        analyzing: "Analyse avec Perplexity + GPT...",
        analyze: "Analyser le Concept",
        result: "Résultat de l'Analyse du Concept",
        edit: "Modifier",
        regenerate: "Régénérer",
        productName: "📦 Nom du Produit",
        usp: "✨ USP (Proposition Unique de Vente)",
        target: "🎯 Cible",
        toneAndManner: "🎨 Ton et Style",
        strategy: "📊 Direction Stratégique",
        marketTrend: "📈 Tendance du Marché",
        keywords: "🏷️ Mots-clés",
        editTitle: "✏️ Modifier le Concept",
        cancel: "Annuler",
        save: "Enregistrer",
        enterPrompt: "Veuillez entrer un prompt",
        generateFailed: "Échec de la génération du concept",
        generateError: "Erreur lors de la génération du concept"
      },
      stepMessage: {
        loading: "GPT rédige les messages...",
        loadingDesc: "Génération du copy optimal basé sur le concept",
        title: "Direction du Message",
        subtitle: "Sélectionnez ou modifiez les copies marketing clés",
        directEdit: "Modification Directe",
        regenerate: "Régénérer",
        mainCopy: "💥 Copy Principal",
        mainCopyDesc: "Le message clé le plus accrocheur",
        subCopy: "📝 Copy Secondaire",
        subCopyDesc: "Description de support pour le copy principal",
        cta: "👆 CTA (Appel à l'Action)",
        ctaDesc: "Bouton/texte qui incite à l'action",
        recommended: "Recommandé",
        editTitle: "✏️ Modifier le Message Directement",
        mainCopyLabel: "Copy Principal",
        subCopyLabel: "Copy Secondaire",
        ctaLabel: "Texte CTA",
        cancel: "Annuler",
        save: "Enregistrer",
        generateFailed: "Échec de la génération du message",
        generateError: "Erreur lors de la génération du message"
      },
      stepScript: {
        loading: "GPT rédige les scripts...",
        loadingDesc: "Génération des histoires Reels, BD, card news",
        title: "Approbation Script/Scénario",
        subtitle: "Révisez le scénario de chaque format de contenu",
        edit: "Modifier",
        regenerate: "Régénérer",
        reelsTiktok: "Reels/TikTok",
        comic: "BD 4 Cases",
        cardnews: "Card News",
        editTitle: "✏️ Modifier le Script",
        editNotice: "La fonction d'édition de script sera bientôt disponible.",
        cancel: "Annuler",
        save: "Enregistrer",
        reelsSceneTitle: "🎬 Scènes Reels/TikTok (10)",
        seconds: "sec",
        comicTitle: "📖 Histoire de la BD 4 Cases",
        panel: "Case",
        cardnewsTitle: "📱 Flux Card News (5 pages)",
        generateFailed: "Échec de la génération du script",
        generateError: "Erreur lors de la génération du script"
      },
      stepCopy: {
        loading: "GPT finalise le copy...",
        loadingDesc: "Organisation du texte final pour chaque format",
        title: "Finalisation du Copy",
        subtitle: "Révisez le texte final pour chaque contenu",
        edit: "Modifier",
        regenerate: "Régénérer",
        reelsCaptions: "🎬 Sous-titres Reels",
        cut: "Scène",
        cardnewsCopies: "📱 Copy Card News",
        page: "Page",
        bannerCopy: "🖼️ Copy Bannière",
        storyCopy: "📲 Copy Story",
        thumbnailTitle: "🎥 Titre Miniature",
        detailPageHeadline: "📄 Titre Page Détail",
        editTitle: "✏️ Modifier le Copy",
        reelsCaptionsLabel: "Sous-titres Reels",
        cardnewsCopiesLabel: "Copy Card News",
        bannerCopyLabel: "Copy Bannière",
        storyCopyLabel: "Copy Story",
        thumbnailTitleLabel: "Titre Miniature",
        detailPageHeadlineLabel: "Titre Page Détail",
        cancel: "Annuler",
        save: "Enregistrer",
        generateFailed: "Échec de la génération du copy",
        generateError: "Erreur lors de la génération du copy"
      },
      stepProduction: {
        title: "Production Auto de Contenu",
        totalImages: "{{count}} images seront générées",
        reels10: "🎬 Reels 10",
        comic4: "📖 BD 4",
        cardnews5: "📱 Card News 5",
        banner2: "🖼️ Bannière 2",
        story2: "📲 Story 2",
        thumbnail3: "🎥 Miniature 3",
        detail2: "📄 Page Détail 2",
        preparing: "Préparation...",
        startProduction: "Démarrer la Production",
        estimatedTime: "Estimé 3-5 min • Sauvegarde auto dans la galerie",
        overallProgress: "Progression Globale",
        reelsLine: "Scènes Reels/TikTok",
        comicLine: "BD 4 Cases",
        cardnewsLine: "Card News",
        bannerLine: "Bannières Pub",
        storyLine: "Stories Pub",
        thumbnailLine: "Miniature YouTube",
        detailLine: "En-tête Page Détail",
        images: "images",
        completed: "Terminé",
        completeTitle: "🎉 Production Terminée !",
        completeDesc: "{{count}} images ont été générées avec succès.",
        completeGuide: "Vérifiez et téléchargez depuis la galerie.",
        startFailed: "Échec du démarrage de la production",
        startError: "Erreur lors du démarrage de la production"
      }
    },
    de: {
      title: "Content Factory",
      subtitle: "Wählen Sie die zu erstellenden Content-Typen",
      productInfo: "Produkt-/Serviceinformationen",
      productInfoPlaceholder: "Geben Sie Produkt-/Serviceinformationen für die Content-Erstellung ein\n\nBeispiel: Ich möchte ein Akne-Behandlungsprogramm einer Dermatologie-Klinik bewerben. Die Zielgruppe sind Frauen im Alter von 20-30 Jahren, und ich möchte trendige, vertrauenswürdige Bilder für Social-Media-Marketing.",
      minChars: "Bitte geben Sie mindestens 10 Zeichen ein",
      selectContentType: "Bitte wählen Sie mindestens 1 Content-Typ",
      start: "Starten",
      selected: "Content-Typen ausgewählt",
      estimatedTime: "Geschätzte Zeit: 2-5 Minuten",
      processTitle: "🏭 5-Schritte Content Factory Prozess",
      step1Name: "Konzept",
      step1Desc: "KI-Produktanalyse und Strategie",
      step2Name: "Nachricht",
      step2Desc: "Automatische Haupt-/Neben-Copy Generierung",
      step3Name: "Skript",
      step3Desc: "Reels, Comic, Card News Szenarien",
      step4Name: "Copy",
      step4Desc: "Text-Finalisierung für jedes Format",
      step5Name: "Produktion",
      step5Desc: "Automatische Generierung aller Bilder",
      pricingTitle: "💰 Content-Preisliste",
      contentTypes: {
        reels: "Reels/TikTok",
        reelsCount: "10 Szenen",
        comic: "4-Panel Comic",
        comicCount: "4 Panels",
        cardnews: "Card News",
        cardnewsCount: "5 Seiten",
        banner: "Banner-Werbung",
        bannerCount: "2 Typen",
        thumbnail: "YouTube Thumbnail",
        thumbnailCount: "3 Typen",
        detail: "Detailseite",
        detailCount: "2 Typen"
      },
      modal: {
        title: "Content Factory",
        subtitle: "Automatische tägliche Content-Generierung",
        step: "Schritt",
        prevStep: "Zurück",
        nextStep: "Weiter",
        generating: "Generierung...",
        complete: "Fertig"
      },
      stepConcept: {
        inputLabel: "💡 Produkt-/Serviceinformationen",
        placeholder: "Beispiel: Ich möchte ein Akne-Behandlungsprogramm einer spezialisierten Dermatologie-Klinik bewerben. Die Zielgruppe sind Frauen im Alter von 20-30 Jahren, und ich plane Social-Media-Marketing mit trendigen, vertrauenswürdigen Bildern.",
        analyzing: "Analyse mit Perplexity + GPT...",
        analyze: "Konzept Analysieren",
        result: "Konzeptanalyse-Ergebnis",
        edit: "Bearbeiten",
        regenerate: "Neu Generieren",
        productName: "📦 Produktname",
        usp: "✨ USP (Alleinstellungsmerkmal)",
        target: "🎯 Zielgruppe",
        toneAndManner: "🎨 Ton & Stil",
        strategy: "📊 Strategische Richtung",
        marketTrend: "📈 Markttrend",
        keywords: "🏷️ Schlüsselwörter",
        editTitle: "✏️ Konzept Bearbeiten",
        cancel: "Abbrechen",
        save: "Speichern",
        enterPrompt: "Bitte geben Sie einen Prompt ein",
        generateFailed: "Konzepterstellung fehlgeschlagen",
        generateError: "Fehler bei der Konzepterstellung"
      },
      stepMessage: {
        loading: "GPT schreibt Nachrichten...",
        loadingDesc: "Optimalen Copy basierend auf dem Konzept generieren",
        title: "Nachrichtenrichtung",
        subtitle: "Wählen oder bearbeiten Sie die wichtigsten Marketing-Copies",
        directEdit: "Direkt Bearbeiten",
        regenerate: "Neu Generieren",
        mainCopy: "💥 Haupt-Copy",
        mainCopyDesc: "Die auffälligste Kernbotschaft",
        subCopy: "📝 Neben-Copy",
        subCopyDesc: "Unterstützende Beschreibung für den Haupt-Copy",
        cta: "👆 CTA (Handlungsaufforderung)",
        ctaDesc: "Button/Text der zur Aktion auffordert",
        recommended: "Empfohlen",
        editTitle: "✏️ Nachricht Direkt Bearbeiten",
        mainCopyLabel: "Haupt-Copy",
        subCopyLabel: "Neben-Copy",
        ctaLabel: "CTA Text",
        cancel: "Abbrechen",
        save: "Speichern",
        generateFailed: "Nachrichtenerstellung fehlgeschlagen",
        generateError: "Fehler bei der Nachrichtenerstellung"
      },
      stepScript: {
        loading: "GPT schreibt Skripte...",
        loadingDesc: "Reels, Comic, Card News Geschichten generieren",
        title: "Skript/Szenario Genehmigung",
        subtitle: "Überprüfen Sie die Storyline für jedes Content-Format",
        edit: "Bearbeiten",
        regenerate: "Neu Generieren",
        reelsTiktok: "Reels/TikTok",
        comic: "4-Panel Comic",
        cardnews: "Card News",
        editTitle: "✏️ Skript Bearbeiten",
        editNotice: "Skript-Bearbeitungsfunktion kommt bald.",
        cancel: "Abbrechen",
        save: "Speichern",
        reelsSceneTitle: "🎬 Reels/TikTok Szenen (10)",
        seconds: "Sek",
        comicTitle: "📖 4-Panel Comic Geschichte",
        panel: "Panel",
        cardnewsTitle: "📱 Card News Ablauf (5 Seiten)",
        generateFailed: "Skripterstellung fehlgeschlagen",
        generateError: "Fehler bei der Skripterstellung"
      },
      stepCopy: {
        loading: "GPT finalisiert Copy...",
        loadingDesc: "Endgültigen Text für jedes Format organisieren",
        title: "Copy Finalisierung",
        subtitle: "Überprüfen Sie den endgültigen Text für jeden Content",
        edit: "Bearbeiten",
        regenerate: "Neu Generieren",
        reelsCaptions: "🎬 Reels Untertitel",
        cut: "Szene",
        cardnewsCopies: "📱 Card News Copy",
        page: "Seite",
        bannerCopy: "🖼️ Banner Copy",
        storyCopy: "📲 Story Copy",
        thumbnailTitle: "🎥 Thumbnail Titel",
        detailPageHeadline: "📄 Detailseiten-Überschrift",
        editTitle: "✏️ Copy Bearbeiten",
        reelsCaptionsLabel: "Reels Untertitel",
        cardnewsCopiesLabel: "Card News Copy",
        bannerCopyLabel: "Banner Copy",
        storyCopyLabel: "Story Copy",
        thumbnailTitleLabel: "Thumbnail Titel",
        detailPageHeadlineLabel: "Detailseiten-Überschrift",
        cancel: "Abbrechen",
        save: "Speichern",
        generateFailed: "Copy-Erstellung fehlgeschlagen",
        generateError: "Fehler bei der Copy-Erstellung"
      },
      stepProduction: {
        title: "Automatische Content-Produktion",
        totalImages: "{{count}} Bilder werden generiert",
        reels10: "🎬 Reels 10",
        comic4: "📖 Comic 4",
        cardnews5: "📱 Card News 5",
        banner2: "🖼️ Banner 2",
        story2: "📲 Story 2",
        thumbnail3: "🎥 Thumbnail 3",
        detail2: "📄 Detailseite 2",
        preparing: "Vorbereitung...",
        startProduction: "Produktion Starten",
        estimatedTime: "Geschätzt 3-5 Min • Automatische Speicherung in der Galerie",
        overallProgress: "Gesamtfortschritt",
        reelsLine: "Reels/TikTok Szenen",
        comicLine: "4-Panel Comic",
        cardnewsLine: "Card News",
        bannerLine: "Banner-Anzeigen",
        storyLine: "Story-Anzeigen",
        thumbnailLine: "YouTube Thumbnail",
        detailLine: "Detailseiten-Header",
        images: "Bilder",
        completed: "Abgeschlossen",
        completeTitle: "🎉 Produktion Abgeschlossen!",
        completeDesc: "{{count}} Bilder wurden erfolgreich generiert.",
        completeGuide: "Überprüfen und herunterladen aus der Galerie.",
        startFailed: "Produktionsstart fehlgeschlagen",
        startError: "Fehler beim Produktionsstart"
      }
    }
  },

  // ===== history =====
  history: {
    ja: {
      title: "📚 生成履歴",
      totalTasks: "{{count}}件の生成タスク",
      total: "全体",
      completed: "完了",
      inProgress: "進行中",
      failed: "失敗",
      statusPending: "⏳ 待機中",
      statusProcessing: "🔄 処理中",
      statusCompleted: "✅ 完了",
      statusFailed: "❌ 失敗",
      noHistory: "生成履歴がありません",
      noHistoryDesc: "最初のAI画像を生成しましょう！",
      generateImage: "画像を生成",
      images: "枚",
      loadMore: "もっと見る"
    },
    zh: {
      title: "📚 生成历史",
      totalTasks: "{{count}}个生成任务",
      total: "全部",
      completed: "已完成",
      inProgress: "进行中",
      failed: "失败",
      statusPending: "⏳ 等待中",
      statusProcessing: "🔄 处理中",
      statusCompleted: "✅ 已完成",
      statusFailed: "❌ 失败",
      noHistory: "没有生成历史",
      noHistoryDesc: "生成您的第一张AI图片吧！",
      generateImage: "生成图片",
      images: "张",
      loadMore: "加载更多"
    },
    es: {
      title: "📚 Historial de Generación",
      totalTasks: "{{count}} tareas de generación",
      total: "Total",
      completed: "Completado",
      inProgress: "En Progreso",
      failed: "Fallido",
      statusPending: "⏳ Pendiente",
      statusProcessing: "🔄 Procesando",
      statusCompleted: "✅ Completado",
      statusFailed: "❌ Fallido",
      noHistory: "Sin historial de generación",
      noHistoryDesc: "¡Genera tus primeras imágenes AI!",
      generateImage: "Generar Imágenes",
      images: "imágenes",
      loadMore: "Cargar Más"
    },
    fr: {
      title: "📚 Historique de Génération",
      totalTasks: "{{count}} tâches de génération",
      total: "Total",
      completed: "Terminé",
      inProgress: "En Cours",
      failed: "Échoué",
      statusPending: "⏳ En Attente",
      statusProcessing: "🔄 En Traitement",
      statusCompleted: "✅ Terminé",
      statusFailed: "❌ Échoué",
      noHistory: "Aucun historique de génération",
      noHistoryDesc: "Générez vos premières images IA !",
      generateImage: "Générer des Images",
      images: "images",
      loadMore: "Charger Plus"
    },
    de: {
      title: "📚 Generierungsverlauf",
      totalTasks: "{{count}} Generierungsaufgaben",
      total: "Gesamt",
      completed: "Abgeschlossen",
      inProgress: "In Bearbeitung",
      failed: "Fehlgeschlagen",
      statusPending: "⏳ Ausstehend",
      statusProcessing: "🔄 Verarbeitung",
      statusCompleted: "✅ Abgeschlossen",
      statusFailed: "❌ Fehlgeschlagen",
      noHistory: "Kein Generierungsverlauf",
      noHistoryDesc: "Generieren Sie Ihre ersten KI-Bilder!",
      generateImage: "Bilder Generieren",
      images: "Bilder",
      loadMore: "Mehr Laden"
    }
  },

  // ===== payment =====
  payment: {
    ja: {
      bankTransfer: {
        title: "銀行振込案内",
        loading: "読み込み中...",
        amount: "振込金額",
        points: "チャージポイント",
        bankInfo: "振込先口座情報",
        bank: "銀行",
        accountNumber: "口座番号",
        accountHolder: "口座名義",
        copyAccount: "口座番号をコピー",
        copied: "コピーしました！",
        depositorName: "振込人名",
        depositorNamePlaceholder: "実際に振り込む方のお名前",
        depositorNameHelp: "確認のため正確に入力してください",
        notice: "ご案内",
        notice1: "入金確認後、手動でポイントがチャージされます（営業日24時間以内）",
        notice2: "振込人名が一致すると迅速な確認が可能です",
        notice3: "入金後確認が取れない場合はお問い合わせください",
        confirmDeposit: "入金完了通知申請",
        submitting: "申請中...",
        submitSuccess: "入金完了申請が受け付けられました。確認後ポイントがチャージされます。",
        submitError: "申請中にエラーが発生しました",
        goHome: "ホームへ"
      },
      success: {
        processing: "決済承認処理中...",
        title: "決済完了！",
        pointsCharged: "{{points}}ポイントがチャージされました！",
        redirecting: "まもなくメインページに移動します...",
        goHome: "ホームへ",
        invalidPayment: "決済情報が正しくありません",
        error: "決済処理中にエラーが発生しました"
      },
      fail: {
        title: "決済失敗",
        errorCode: "エラーコード",
        unknownError: "不明なエラーが発生しました",
        retry: "再試行",
        goHome: "ホームへ",
        needHelp: "問題が続いていますか？"
      }
    },
    zh: {
      bankTransfer: {
        title: "银行转账指南",
        loading: "加载中...",
        amount: "转账金额",
        points: "充值积分",
        bankInfo: "银行账户信息",
        bank: "银行",
        accountNumber: "账号",
        accountHolder: "账户名",
        copyAccount: "复制账号",
        copied: "已复制！",
        depositorName: "汇款人姓名",
        depositorNamePlaceholder: "实际汇款人的姓名",
        depositorNameHelp: "请准确输入以便确认",
        notice: "注意事项",
        notice1: "确认入账后将手动充值积分（工作日24小时内）",
        notice2: "汇款人姓名一致可加快确认速度",
        notice3: "如入账后未确认，请联系客服",
        confirmDeposit: "提交入账通知",
        submitting: "提交中...",
        submitSuccess: "入账通知已提交。确认后将充值积分。",
        submitError: "提交时出错",
        goHome: "返回首页"
      },
      success: {
        processing: "处理支付中...",
        title: "支付完成！",
        pointsCharged: "{{points}}积分已充值！",
        redirecting: "即将跳转到首页...",
        goHome: "返回首页",
        invalidPayment: "支付信息无效",
        error: "支付处理时出错"
      },
      fail: {
        title: "支付失败",
        errorCode: "错误代码",
        unknownError: "发生未知错误",
        retry: "重试",
        goHome: "返回首页",
        needHelp: "问题仍然存在？"
      }
    },
    es: {
      bankTransfer: {
        title: "Guía de Transferencia Bancaria",
        loading: "Cargando...",
        amount: "Monto a Transferir",
        points: "Puntos a Cargar",
        bankInfo: "Información de Cuenta Bancaria",
        bank: "Banco",
        accountNumber: "Número de Cuenta",
        accountHolder: "Titular de la Cuenta",
        copyAccount: "Copiar Cuenta",
        copied: "¡Copiado!",
        depositorName: "Nombre del Depositante",
        depositorNamePlaceholder: "Nombre de quien realiza el depósito",
        depositorNameHelp: "Por favor ingrese con precisión para verificación",
        notice: "Aviso",
        notice1: "Los puntos se acreditarán manualmente después de confirmar el depósito (dentro de 24 horas hábiles)",
        notice2: "El nombre del depositante debe coincidir para verificación rápida",
        notice3: "Contacte soporte si no se confirma después del depósito",
        confirmDeposit: "Notificar Depósito Completado",
        submitting: "Enviando...",
        submitSuccess: "Notificación de depósito enviada. Los puntos se acreditarán después de la verificación.",
        submitError: "Error al enviar",
        goHome: "Ir al Inicio"
      },
      success: {
        processing: "Procesando pago...",
        title: "¡Pago Completado!",
        pointsCharged: "¡{{points}} puntos han sido cargados!",
        redirecting: "Redirigiendo a la página principal...",
        goHome: "Ir al Inicio",
        invalidPayment: "Información de pago inválida",
        error: "Error al procesar el pago"
      },
      fail: {
        title: "Pago Fallido",
        errorCode: "Código de Error",
        unknownError: "Ocurrió un error desconocido",
        retry: "Reintentar",
        goHome: "Ir al Inicio",
        needHelp: "¿Sigue teniendo problemas?"
      }
    },
    fr: {
      bankTransfer: {
        title: "Guide de Virement Bancaire",
        loading: "Chargement...",
        amount: "Montant du Virement",
        points: "Points à Créditer",
        bankInfo: "Informations Bancaires",
        bank: "Banque",
        accountNumber: "Numéro de Compte",
        accountHolder: "Titulaire du Compte",
        copyAccount: "Copier le Compte",
        copied: "Copié !",
        depositorName: "Nom du Déposant",
        depositorNamePlaceholder: "Nom de la personne effectuant le dépôt",
        depositorNameHelp: "Veuillez entrer avec précision pour vérification",
        notice: "Avis",
        notice1: "Les points seront crédités manuellement après confirmation du dépôt (dans les 24 heures ouvrables)",
        notice2: "Le nom du déposant doit correspondre pour une vérification rapide",
        notice3: "Contactez le support si non confirmé après le dépôt",
        confirmDeposit: "Notifier le Dépôt Effectué",
        submitting: "Envoi...",
        submitSuccess: "Notification de dépôt envoyée. Les points seront crédités après vérification.",
        submitError: "Erreur lors de l'envoi",
        goHome: "Aller à l'Accueil"
      },
      success: {
        processing: "Traitement du paiement...",
        title: "Paiement Effectué !",
        pointsCharged: "{{points}} points ont été crédités !",
        redirecting: "Redirection vers la page d'accueil...",
        goHome: "Aller à l'Accueil",
        invalidPayment: "Informations de paiement invalides",
        error: "Erreur lors du traitement du paiement"
      },
      fail: {
        title: "Paiement Échoué",
        errorCode: "Code d'Erreur",
        unknownError: "Une erreur inconnue s'est produite",
        retry: "Réessayer",
        goHome: "Aller à l'Accueil",
        needHelp: "Vous avez toujours des problèmes ?"
      }
    },
    de: {
      bankTransfer: {
        title: "Banküberweisung Anleitung",
        loading: "Laden...",
        amount: "Überweisungsbetrag",
        points: "Aufzuladende Punkte",
        bankInfo: "Bankkontoinformationen",
        bank: "Bank",
        accountNumber: "Kontonummer",
        accountHolder: "Kontoinhaber",
        copyAccount: "Konto Kopieren",
        copied: "Kopiert!",
        depositorName: "Einzahlername",
        depositorNamePlaceholder: "Name der Person, die einzahlt",
        depositorNameHelp: "Bitte für die Verifizierung genau eingeben",
        notice: "Hinweis",
        notice1: "Punkte werden nach Einzahlungsbestätigung manuell gutgeschrieben (innerhalb von 24 Geschäftsstunden)",
        notice2: "Der Einzahlername muss für schnelle Verifizierung übereinstimmen",
        notice3: "Kontaktieren Sie den Support, wenn nach der Einzahlung nicht bestätigt",
        confirmDeposit: "Einzahlung Bestätigen",
        submitting: "Wird gesendet...",
        submitSuccess: "Einzahlungsbenachrichtigung gesendet. Punkte werden nach Verifizierung gutgeschrieben.",
        submitError: "Fehler beim Senden",
        goHome: "Zur Startseite"
      },
      success: {
        processing: "Zahlung wird verarbeitet...",
        title: "Zahlung Abgeschlossen!",
        pointsCharged: "{{points}} Punkte wurden gutgeschrieben!",
        redirecting: "Weiterleitung zur Startseite...",
        goHome: "Zur Startseite",
        invalidPayment: "Ungültige Zahlungsinformationen",
        error: "Fehler bei der Zahlungsverarbeitung"
      },
      fail: {
        title: "Zahlung Fehlgeschlagen",
        errorCode: "Fehlercode",
        unknownError: "Ein unbekannter Fehler ist aufgetreten",
        retry: "Erneut Versuchen",
        goHome: "Zur Startseite",
        needHelp: "Haben Sie immer noch Probleme?"
      }
    }
  },

  // ===== verifyEmail =====
  verifyEmail: {
    ja: {
      title: "メール認証",
      checkEmail: "メールをご確認ください",
      sentTo: "{{email}}に認証メールを送信しました。",
      checkSpam: "メールが見つからない場合は迷惑メールフォルダをご確認ください。",
      resend: "認証メール再送信",
      sending: "送信中...",
      resendSuccess: "✅ 認証メールが送信されました！受信トレイをご確認ください。",
      resendError: "❌ 認証メールの送信に失敗しました。",
      tooManyRequests: "❌ リクエストが多すぎます。しばらくしてから再試行してください。",
      alreadySent: "📧 すでに送信された認証メールをご確認ください。",
      verified: "認証完了！",
      verifiedDesc: "メール認証が完了しました。",
      goHome: "ホームへ",
      checkVerification: "認証確認",
      askResend: "メール認証が必要です。\n\n認証メールを再送信しますか？"
    },
    zh: {
      title: "邮箱验证",
      checkEmail: "请查收您的邮件",
      sentTo: "验证邮件已发送至{{email}}。",
      checkSpam: "如果没有收到，请检查垃圾邮件文件夹。",
      resend: "重新发送验证邮件",
      sending: "发送中...",
      resendSuccess: "✅ 验证邮件已发送！请查收。",
      resendError: "❌ 发送验证邮件失败。",
      tooManyRequests: "❌ 请求次数过多。请稍后再试。",
      alreadySent: "📧 请查收已发送的验证邮件。",
      verified: "验证成功！",
      verifiedDesc: "邮箱验证已完成。",
      goHome: "返回首页",
      checkVerification: "检查验证状态",
      askResend: "需要邮箱验证。\n\n是否重新发送验证邮件？"
    },
    es: {
      title: "Verificación de Email",
      checkEmail: "Por favor revisa tu email",
      sentTo: "Email de verificación enviado a {{email}}.",
      checkSpam: "Revisa tu carpeta de spam si no lo ves.",
      resend: "Reenviar Email de Verificación",
      sending: "Enviando...",
      resendSuccess: "✅ ¡Email de verificación enviado! Por favor revisa tu bandeja de entrada.",
      resendError: "❌ Error al enviar el email de verificación.",
      tooManyRequests: "❌ Demasiadas solicitudes. Por favor intenta más tarde.",
      alreadySent: "📧 Por favor revisa el email de verificación ya enviado.",
      verified: "¡Verificado!",
      verifiedDesc: "Verificación de email completada.",
      goHome: "Ir al Inicio",
      checkVerification: "Verificar Estado",
      askResend: "Se requiere verificación de email.\n\n¿Deseas reenviar el email de verificación?"
    },
    fr: {
      title: "Vérification Email",
      checkEmail: "Veuillez vérifier votre email",
      sentTo: "Email de vérification envoyé à {{email}}.",
      checkSpam: "Vérifiez votre dossier spam si vous ne le voyez pas.",
      resend: "Renvoyer l'Email de Vérification",
      sending: "Envoi...",
      resendSuccess: "✅ Email de vérification envoyé ! Veuillez vérifier votre boîte de réception.",
      resendError: "❌ Échec de l'envoi de l'email de vérification.",
      tooManyRequests: "❌ Trop de demandes. Veuillez réessayer plus tard.",
      alreadySent: "📧 Veuillez vérifier l'email de vérification déjà envoyé.",
      verified: "Vérifié !",
      verifiedDesc: "Vérification email terminée.",
      goHome: "Aller à l'Accueil",
      checkVerification: "Vérifier l'État",
      askResend: "Vérification email requise.\n\nVoulez-vous renvoyer l'email de vérification ?"
    },
    de: {
      title: "E-Mail Verifizierung",
      checkEmail: "Bitte überprüfen Sie Ihre E-Mail",
      sentTo: "Verifizierungs-E-Mail an {{email}} gesendet.",
      checkSpam: "Überprüfen Sie Ihren Spam-Ordner, wenn Sie sie nicht sehen.",
      resend: "Verifizierungs-E-Mail Erneut Senden",
      sending: "Wird gesendet...",
      resendSuccess: "✅ Verifizierungs-E-Mail gesendet! Bitte überprüfen Sie Ihren Posteingang.",
      resendError: "❌ Fehler beim Senden der Verifizierungs-E-Mail.",
      tooManyRequests: "❌ Zu viele Anfragen. Bitte versuchen Sie es später erneut.",
      alreadySent: "📧 Bitte überprüfen Sie die bereits gesendete Verifizierungs-E-Mail.",
      verified: "Verifiziert!",
      verifiedDesc: "E-Mail-Verifizierung abgeschlossen.",
      goHome: "Zur Startseite",
      checkVerification: "Verifizierung Prüfen",
      askResend: "E-Mail-Verifizierung erforderlich.\n\nMöchten Sie die Verifizierungs-E-Mail erneut senden?"
    }
  }
};

// 메인 함수
async function syncTranslations() {
  const languages = ['ja', 'zh', 'es', 'fr', 'de'];
  
  for (const lang of languages) {
    const filePath = path.join(LOCALES_DIR, `${lang}.json`);
    
    // 기존 파일 읽기
    let existingData = {};
    try {
      const content = fs.readFileSync(filePath, 'utf8');
      existingData = JSON.parse(content);
    } catch (error) {
      console.error(`Error reading ${lang}.json:`, error);
      continue;
    }
    
    // 새 번역 데이터 추가
    const newData = { ...existingData };
    
    // contentFactory 추가
    if (translations.contentFactory[lang]) {
      newData.contentFactory = translations.contentFactory[lang];
    }
    
    // history 추가
    if (translations.history[lang]) {
      newData.history = translations.history[lang];
    }
    
    // payment 추가
    if (translations.payment[lang]) {
      newData.payment = translations.payment[lang];
    }
    
    // verifyEmail 추가
    if (translations.verifyEmail[lang]) {
      newData.verifyEmail = translations.verifyEmail[lang];
    }
    
    // 파일 쓰기
    fs.writeFileSync(filePath, JSON.stringify(newData, null, 2), 'utf8');
    console.log(`✅ ${lang}.json 업데이트 완료`);
  }
  
  console.log('\n🎉 모든 번역 파일 동기화 완료!');
}

syncTranslations();


